name: JIRA Ticket Validation
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  jira-validation:
    uses: IPSI-AU/es-devops/.github/workflows/jira-validation-reusable.yml@master